
let proyectos = {
    lista_proyectos: [
        {
            n: "Modalidad F3",
            o: "Masificar la participación de todos",
            d: "En crear una página anexada al instagram del CEE, en la que todos nuestros compañeros puedan dar su opinión de manera constructiva",
            lu: "Internet",
            ar: "IC",
            pr: 100
        },{
            n: "CEE informa" ,
            o: "Tener nuestra propia página web",
            d: "Crear página web del centro de estudiantes, mediante la cual daremos a conocer los porcentajes de avances de nuestros proyectos, imágenes de actividades e información de valor para la comunidad estudiantil.",
            lu: "Internet" ,
            ar: "IC",
            pr: 100,
        },{
            n: "¡¡Quiero participar!!",
            o: "Promover la participación de más personas en los futuros CEE",
            d: "Generar un documento en el que todos los alumnos se puedan inscribir para formar parte de posibles CEE. Para que a la hora de que alguien comience a crear su lista, entre al documento y se contacte con las personas que quieran en su lista de manera más fácil",
            lu: "Estará anexado al instagram del CEE",
            ar: "IC",
            pr: 70,
        },{
            n: "Estudiemos juntos" ,
            o: "Facilitar el estudio de cada uno de nosotros",
            d: "Subiremos a la página web del CEE tips de estudio, apuntes y guías que les puedan servir más adelante y así nos ayudamos entre todos.",
            lu: "Página web de CEE",
            ar: "IC",
            pr: 100,
        },{
            n: "Regalo Cuartos Medios" ,
            o: "Otorgar recuerdo de despedida para los compañeros de cuarto medio",
            d: "Seguir con la tradició y encargar los globos para los compañeros egresados de este año, como símbolo de finalización de su vida escolar." ,
            lu: "Colegio" ,
            ar: "IC",
            pr: 100,
        },{
            n: "Participar en el paso de sección (segundo a tercero básico)",
            o: 'Generar un buen ambiente, lleno de alegría para los pequeños que se cambian de cruzan al “colegio del frente”' ,
            d: "Esperar a los niños de segundo básico en su nueva sección y recibirlos con globos y aplausos",
            lu: "Hall del colegio",
            ar: "IC",
            pr: 100,
        },{
            n: "Mural CEE",
            o: "Dar a conocer lo que hacemos a los apoderados"  ,
            d: "Enviar un mural digital para los apoderados, mostrando nuestros proyectos ya realizados" ,
            lu: "Correos",
            ar: "IC",
            pr: 45,
        },{
            n: "Todos con la parroquia" ,
            o: "Entregar mayor apoyo a parroquia San Francisco y promover la participación" ,
            d: "Ayudar a la parroquia con sus proyectos solidarios" ,
            lu: "Parroquia San Francisco e instagram CEE",
            ar: "PA",
            pr: 100,
        },{
            n: "Día del niñx",
            o: "Entregar un buen lindo momento a los niños de la parroquia San Francisco" ,
            d: "Recolectar regalos y hacer bolsas con dulces para los niños de la parroquia San Francisco y dárselos en su día" ,
            lu: "Asilo que se elija" ,
            ar: "PA",
            pr: 100,
        },{
            n: "Misa CEE",
            o: "Realizar la misa anual del CEE" ,
            d: "Hacer la misa anual a cargo del CEE",
            lu: "Capilla colegial",
            ar: "PA",
            pr: 100,
        },{
            n: "Publicitar Emprendedores Maristas",
            o: "Ayudar familias maristas promocionando sus servicios",
            d: "Subir a nuestro instagram todos los emprendimientos maristas",
            lu: "Instagram CEE",
            ar: "PA",
            pr: 100,
        },{
            n: "Compañerx del Semestre"  ,
            o: "Reconocer a personas que aporten a la buena convivencia en su curso",
            d: "Cada curso votará por el/la compañerx que consideren que mantuvo y promovió la buena convivencia de su curso dentro del semestre, para luego subir los ganadores a nuestro instagram" ,
            lu: "Instagram CEE",
            ar: "CB",
            pr: 100,
        },{
            n: "Regala una sonrisa"  ,
            o: "Alegrar a un compañero",
            d: "Si alguien ve a un compañero suyo triste, nos puede enviar un mensaje positivo a nuestro instagram para que se lo mandemos a ella/él de forma anónima a su instagram" ,
            lu: "Instagram CEE",
            ar: "CB",
            pr: 100,
        },{
            n: "Dispensador de toallitas higiénicas"  ,
            o: "Otorgar mayor comodidad a nuestras compañeras en los baños",
            d: "Colocar un dispensador de toallitas higiénicas en los baños, para uso de emergencia",
            lu: "Baños femeninos media inicial, media superior y básica" ,
            ar: "CB",
            pr: 78,
        },{
            n: "Votar temáticas de alianzas" ,
            o: "Escuchar las ideas de nuestros compañeros para las alianzas",
            d: "Realizar las alianzas ya sean virtuales o presenciales, con la diferencia de que someteremos a votación las temáticas de los equipos y actividades a realizar",
            lu: "Colegio y votaciones virtuales" ,
            ar: "CB",
            pr: 100,
        },
        {
            n: "Votación para próximas charlas" ,
            o: "Abrir nuestras mentes" ,
            d: "Todos los compañeros votaremos por temas de interés general y la haremos llegar al CODI" ,
            lu: "Modalidad híbrida" ,
            ar: "FC",
            pr: 100,
        },{
            n: "Cuenta pública",
            o: "Promover la participación y comunicación directa en todos los compañeros" ,
            d: "Realizar una cuenta pública a final del periodo como CEE con todos los alumnos desde séptimo a cuarto medio",
            lu: "Virtual y si se puede presenciar el patio de media inicial" ,
            ar: "FC",
            pr: 78,
        },{
            n: "¿Qué opino?" ,
            o: "Promover la opinión de todos nuestros compañeros y mostrar diversos puntos de vista",
            d: "Elegir un tema actual y subir a las historias de instagram encuestas pidiendo la opinión de todos, para luego exponerlas en un debate virtual",
            lu: "Modalidad virtual" ,
            ar: "FC",
            pr: 60,
        },{
            n: "Publicitar grupos estudiantiles e informativos"  ,
            o: "Dar a conocer diversos grupos colegiales que tratan temas interesantes y así promover la participación en ellos" ,
            d: "Publicaremos en instagram grupos que traten temas actuales (ej CDG, MERCH, Avanzado de Historia) Además de dar a conocer su trabajo" ,
            lu: "Online" ,
            ar: "FC",
            pr: 100,
        },{
            n: "¿Cómo actúo?",
            o: "Informar y preparar a todos para diversas situaciones" ,
            d: "Subiremos a nuestra página web videos de cómo actuar en diversas situaciones a las que podríamos enfrentarnos en algún momento de nuestras vidas." ,
            lu: "Instagram CEE",
            ar: "FC",
            pr: 100,
        },
        {
        n: "Navidad Solidaria",
        o: "Brindar una bonita navidad a los niños de la parroquia San Francisco",
        d: "Colocar puestos de juegos e interacción para los niños que asistan", 
        lu: "Estadio Marista",
        ar: "SL",
        pr: 60,
        },{
        n: "Todos con el PREUCH",
        o: "Apoyar al preuniversitario solidario" ,
        d: "Promocionar al preuniversitario para entusiasmar posibles y futuros profesores." ,
        lu: "Colegio" ,
        ar: "SL",
        pr: 100,
        },{
        n: "Lotería Solidaria" ,
        o: "Apoyar como CEE en el Bingo solidario",
        d: "Dependiendo de las circunstancias ayudaremos a promocionar la compra de bingos por nuestro instagram y luego a que se lleve a cabo la lotería" ,
        lu:	"Colegio y online", 
        ar: "SL",
        pr:100,    
        },
        {
        n:	"Ladrillos ecológicos" ,
        o:	"Fomentar el cuidado medioambiental", 
        d:	"Enseñar con respecto a cómo hacer ladrillos ecológicos", 
        lu:	"Patios media inicial y superior",
        ar: "EC",
        pr: 50},

{n:	"Trae tu botella",
o:	"Promover la vida sana",
d:	"Hacer jugos naturales para todxs los que traigan su botella", 
lu:	"Patio media inicial y superior",
ar: "EC",
pr: 78,},

{n: 	"Reciclar Papeles",
o:	"Promover el reciclaje e incentivar la participación",
d:	"En el patio de media inicial y superior se colocarán botes para papeles. Cada sala tendrá una bolsa de género y un encargado rotatorio que acumule los papeles de su sala en la bolsa, para luego ir a dejarlos al recipiente.",
lu:	"Patios de sección básica, media inicial y superior.",
ar: "EC",
pr: 100,},

{n:	"Reciclar productos electrónicos" ,
o:	"Fomentar el reciclaje.",
d:	"Cada curso se encargará de separar sus productos los que luego nos llevaremos a un centro de reciclaje, el curso que obtenga más objetos se ganará un premio.",
lu:	"Patios de sección básica, media inicial y superior.",
ar: "EC",
pr: 10,},

{n:	"Rediseñar la ropa usada"  ,
o:	"Instaurar un nuevo pensamiento; la ropa vieja no se vota.",
d:	"Haremos un tutorial de cómo modificar nuestra ropa vieja",
lu:	"instagram CEE.",
ar: "EC",
pr: 40,},

{n:  "Reciclar pilas"  ,
o:	"Promover el reciclaje" ,
d:	"Reuniremos pilas para luego llevarlas a un punto de reciclaje, ya que las pilas son un gran foco contaminante de la actualidad.",
lu:	"Sección básica, media inicial y superior",
ar: "EC",
pr: 100,},

{n:  "Reciclar tapas"  ,
o:	"Promover el reciclaje" ,
d:	"Pediremos a cada curso recolección de tapas para luego entregarlas a un centro de reciclaje" ,
lu:	"Sección media inicial y superior" ,
ar: "EC",
pr: 100,},

{n:	"Café concert" ,
o:	"Entregar espacios para los músicos del colegio",
d:	"Habilitaremos el patio de la sección media inicial con mesas y sillas, para la presentación de diversos artistas. Mientras el público disfruta de alimentos vendidos por el CEE." ,
lu:	"Patio de media inicial",
ar: "CL",
pr: 100,},

{n:	"Promoción del Encuentro Artístico" ,
o:	"Dar a conocer lo que suceda en el encuentro artístico",
d:	"Subir a nuestra página los horarios y la promoción de nuestros artístas que participarán en el encuentro artístico." ,
lu:	"Instagram CEE",
ar: "CL",
pr: 100,},

{n: 	"Recreos Artísticos" ,
o:	"Dar lugar a que conozcamos artistas del colegio",
d:	"Cada cierto tiempo en los recreos pediremos voluntarios para realizar intervenciones artísticas. De igual forma para no excluir a las personas que no vayan presencial transmitiremos en vivo las intervenciones." ,
lu:	"Patio media inicial y superior",
ar: "CL",
pr: 100,},

{n:	"Semana del Arte" ,
o:	"Aumentar los espacios artísticos en el colegio",
d:	"Realizar durante una semana intervenciones artísticas en recreos y en la tarde tener la actividad de café concert (todo será transmitido en vivo)",
lu:	"Patios media inicial y superior",
ar: "CL",
pr: 100,},

{n:	"Feria científica"  ,
o:	"Fomentar las ciencias en el colegio",
d:	"Realizar una exposición científica de los alumnos que quieran mostrar algún proyecto (física, química, biología, etc).",
lu:	"Patio de media inicial",
ar: "CL",
pr: 78,},


{n: 	"Torneos Virtuales con otros Colegios",
o:	"Acercarnos y unirnos más a través de juegos", 
d:	"Realizar un torneo de los 2 video juegos más votados, y luego los ganadores competirán virtualmente con los ganadores de otros colegios, para determinar al mejor de Rancagua." ,
lu:	"Online" ,
ar: "RP",
pr: 100,},

{n: 	"Tu pasión en una pared",
o:	"Tener un sector del colegio que nos represente e inspire a todos" ,
d:	"Se nos otorgará una pared en algún sector del colegio, donde cada rama deportiva, artística, cultural y pastoral" ,
lu:	"Pared colegial" ,
ar: "RP",
pr: 78,},

{n:	"Días Temáticos" ,
o:	"Tener días distintos" ,
d:	"Se votarán temáticas para venir vestidos el penúltimo día de clases",
lu:	"Colegio" ,
ar: "RP",
pr: 50,},

{n: "	Olimpiadas internas",
o:	"Unir a todos los compañeros con actividades en conjunto"  ,
d:	"Se formarán equipos por curso, quienes se enfrentarán en las tardes con el deporte escogido." ,
lu:	"Colegio" ,
ar: "RP",
pr: 70,},





{n:	"Recreos musicales" ,
o:	"Alegrar los recreos" ,
d:	"Poner música en los patios de media inicial y superior" ,
lu:	"Patios de media inicial y superior",
ar: "RP",
pr: 100,},


{n: 	"Campeonato General" ,
o:	"Unir a través del deporte" ,
d:	"Se votará por un deporte y luego se harán torneos por cursos en las tardes. También serán transmitidos.",
lu:	"Patio de básica y gimnasios" ,
ar: "RP",
pr: 40,},

{n:	"Torneo de ping pong",
o:	"Promocionar este deporte" ,
d:	"Es un campeonato de ping pong entre alumnos desde séptimo básico a cuarto medio, en el que mostrarán sus habilidades y representaran a su curso." ,
lu:	"Colegio" ,
ar: "DP",
pr: 100,},


{n:	"Mini torneos" ,
o:	"Hacer que los recreos sean distintos ciertos días" ,
d:	"Realizar competencias de lagartijas, triples, sentadillas y carreras en los recreos.",
lu:	"Recreos",
ar: "DP",
pr: 100,},

{n:	"Torneo de ajedrez" ,
o:	"Dar espacios a actividades deportivas distintas" ,
d:	"Campeonatos de ajedrez , el/la ganador/a tendrá un premio, junto con los que ganen segundo y tercer lugar.", 
lu:	"online",
ar: "DP",
pr: 100},

{n:	"Promoción de olimpiadas" ,
o:	"Dar a conocer las olimpiadas maristas" ,
d:	"Promocionar las olimpiadas maristas, cada una de sus ramas, y seguirlos en sus respectivos lugares de competencia.", 
lu:	"instagram del CEE",
ar: "DP",
pr: 100,},

{n:	"Día de la rosa" ,
o:	"Generar ingresos para los proyectos CEE" ,
d:	"Vender rosas a nuestros compañeros con diversos significados y así generar ingresos para los proyectos CEE.", 
lu:	"Colegio",
ar: "TR",
pr: 100,},

{n:	"Cine a un metro" ,
o:	"Unir a nuestros compañeros a con una noche de película" ,
d:	"Organizar un cine dentro del colegio y acompañar la valada con cabritas y bebida.", 
lu:	"Colegio",
ar: "TR",
pr: 100,}
        
    ],
    areas: {
        "IC" : 'Interior y comunicaciones',
        "PA" : 'Pastoral',
        "CB" : 'Convivencia y bienestar',
        "FC" : 'Formación cívica',
        "SL" : 'Solidaridad',
        "EC" : 'Ecología',
        "CL" : 'Cultura',
        "RP" : 'Relaciones públicas',
        "DP" : 'Deportes',
        "TR" : 'Tesorería'
    }
}

export default proyectos